language: java
jdk: oraclejdk7



script:
- ./test.sh
- mvn test -Dselenium

after_success:
  echo 'Send to GAE'

notificatios:
  email:
      recipients:
         - rodrigo.magalhaes@dextra-sw.com



