language: java
jdk: oraclejdk7

addons:
   firefox: "23.0"
services:
  - selenium
before_script:
  - "export DISPLAY=:99.0"
  - "/etc/init.d/xvfb start"
after_script:
  - "/etc/init.d/xvfb stop"

notifications:
  email:
      recipients:
         - rodrigo.magalhaes@dextra-sw.com



