language: java
jdk: oraclejdk7

before_script:
- mvn com.googlecode.mycontainer:mycontainer-maven-plugin:phantomjs-install -Dmycontainer.phantomjs.dest=target/phantomjs -Dmycontainer.phantomjs.version=1.9.2

script:
- mvn test -Dselenium

after_success:
  echo 'Send to GAE'

notificatios:
  email:
      recipients:
         - rodrigo.magalhaes@dextra-sw.com



